"""
test_sk_classifier_stratified_kfold.py

Test stratified k-fold cross-validation of the scikit-learn classifier (Random Forest)
using synthetic SRS data generated by HSI_Labeled_Dataset.

Data is loaded via create_dataloaders() from core.hsi_labeled_dataset, which creates
balanced per-class train/val/test splits.  The train and val subsets are combined into
a single pool that is then evaluated with StratifiedKFold.
"""

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, log_loss
from sklearn.metrics import f1_score
import shap
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os


import sys 
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.hsi_labeled_dataset import HSI_Labeled_Dataset, create_dataloaders

def loader_to_numpy(loader):
    X, y = zip(*[(X.numpy(), y.numpy()) for X, y in loader])
    return np.concatenate(X), np.concatenate(y)

def compute_sam_weights(query_spectra, reference_spectra):
    """
    Compute Spectral Angle Mapper (SAM) similarity weights between query and reference spectra.
    
    Args:
        query_spectra: numpy array of shape (n_query, n_features)
        reference_spectra: numpy array of shape (n_reference, n_features)
        
    Returns:
        sam_weights: numpy array of shape (n_query, n_reference) containing SAM-based weights
    """
    # Normalize spectra
    query_norm = query_spectra / (np.linalg.norm(query_spectra, axis=1, keepdims=True) + 1e-10)  # Add small value to avoid division by zero
    ref_norm = reference_spectra / (np.linalg.norm(reference_spectra, axis=1, keepdims=True) + 1e-10)
    
    # Compute cosine similarity via dot product
    similarity = np.dot(query_norm, ref_norm.T)
    
    # Clip to valid range and compute spectral angle
    cos_sim_matrix = np.clip(similarity, -1, 1)
    thetas = np.arccos(cos_sim_matrix)
    
    # Convert angles to weights (smaller angle = higher weight)
    # Normalized to [0, 1] where 1 is perfect match
    sam_weights = 1 - (thetas / np.pi)
    
    return sam_weights

def plot_SHAP_stability(fold_importance, class_name, top_n_features, output_dir):
    """
    Plot the stability of SHAP feature importance across folds for a given class.

    Args:
        fold_importance: List of per-fold mean |SHAP| arrays for one class (shape: [n_folds, n_features])
        class_name: Name of the class for which to plot feature importance
        top_n_features: Number of top features to display
        output_dir: Directory to save the plot
    """
    importance_array = np.array(fold_importance)  # Shape: (n_folds, n_features)
    df = pd.DataFrame(importance_array.T, columns=[f'Fold {i+1}' for i in range(importance_array.shape[0])])

    # Calculate mean importance
    df['Mean'] = df.mean(axis=1)
    df_top = df.sort_values('Mean', ascending=False).head(top_n_features)
    df_top = df_top.drop(columns='Mean').T  # Transpose for plotting

    # Scale each fold's importance to [0, 1] for better visualization
    df_norm = (df_top - df_top.min()) / (df_top.max() - df_top.min())

    # Plot heatmap of normalized importance
    plt.figure(figsize=(10, 6))
    sns.heatmap(df_norm, annot=True, cmap='viridis', cbar_kws={'label': 'Relative SHAP Importance'})
    plt.title(f'SHAP Feature Importance Stability for Class: {class_name}', fontweight='bold')
    plt.xlabel('Features', fontweight='bold')
    plt.ylabel('Folds', fontweight='bold')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plot_path = os.path.join(output_dir, f'shap_stability_{class_name}.png')
    plt.savefig(plot_path)
    plt.close()


def train_calibrated_model(fitted_model, X_cal, y_cal):
    """Wrap an already-fitted model with Platt scaling (sigmoid calibration) on a held-out set.

    Uses cv='prefit' so the base estimator is not re-fitted — only the sigmoid layer is trained.

    Args:
        fitted_model: A pre-fitted sklearn estimator
        X_cal: Calibration features (held-out from the fold's training set)
        y_cal: Calibration labels
    """
    calibrated_model = CalibratedClassifierCV(fitted_model, cv='prefit', method='isotonic')
    calibrated_model.fit(X_cal, y_cal)
    return calibrated_model


def main():
    # ---------------------------------------------------------------------------
    # Configuration
    # ---------------------------------------------------------------------------
    MOLECULE_DATASET_PATH = 'molecule_dataset/lipid_subtype_wn_61_test'
    SRS_PARAMS_PATH       = 'params_dataset/srs_params_61'
    NUM_SAMPLES_PER_CLASS = 1000    # Keep small for a quick test; increase as needed
    BATCH_SIZE            = 256
    N_FOLDS               = 5
    TRAIN_RATIO           = 0.70
    VAL_RATIO             = 0.15   # remaining 0.15 becomes the held-out test set
    RANDOM_STATE          = 42

    RF_PARAMS = dict(
        n_estimators=79,
        max_depth=26,
        min_samples_split=5,
        min_samples_leaf=4,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    output_dir = 'cross_validation_results'
    os.makedirs(output_dir, exist_ok=True)
    # ---------------------------------------------------------------------------
    # 1. Build dataset and dataloaders
    # ---------------------------------------------------------------------------
    #Load the dataset 
    dataset = HSI_Labeled_Dataset(
        molecule_dataset_path=MOLECULE_DATASET_PATH,
        srs_params_path=SRS_PARAMS_PATH,
        num_samples_per_class=NUM_SAMPLES_PER_CLASS,
        normalize_per_molecule=False,
        compute_min_max=True,
    )

    train_loader, val_loader, test_loader = create_dataloaders(
        dataset,
        batch_size=BATCH_SIZE,
        train_ratio=TRAIN_RATIO,
        val_ratio=VAL_RATIO,
        seed=RANDOM_STATE,
    )

    # ---------------------------------------------------------------------------
    # 2. Extract numpy arrays from loaders
    #    Train + Val are pooled as the cross-validation set; Test is held out.
    # ---------------------------------------------------------------------------

    print("EXTRACTING FEATURES FROM DATALOADERS")

    X_cv, y_cv     = loader_to_numpy(train_loader)
    X_val, y_val   = loader_to_numpy(val_loader)
    X_test, y_test = loader_to_numpy(test_loader)

    # Pool train + val for cross-validation
    X_cv = np.vstack([X_cv, X_val])
    y_cv = np.concatenate([y_cv, y_val])

    print(f"\nCross-validation pool : {X_cv.shape[0]} samples")
    print(f"Held-out test set     : {X_test.shape[0]} samples")

    # ---------------------------------------------------------------------------
    # 3. Stratified K-Fold cross-validation
    # ---------------------------------------------------------------------------

    print(f"STRATIFIED {N_FOLDS}-FOLD CROSS-VALIDATION")

    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=RANDOM_STATE)

    fold_accuracies = []
    fold_scores = []


    fold_importance = []

    # Fetch reference library once outside the fold loop (static data)
    reference_library_array, label_array = dataset.get_reference()

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_cv, y_cv)):
        print(f"\n-- Fold {fold + 1}/{N_FOLDS} --")

        X_tr, X_vl = X_cv[train_idx], X_cv[val_idx]
        y_tr, y_vl = y_cv[train_idx], y_cv[val_idx]

        # Split train into fit set + calibration set (80/20)
        cal_split = int(len(X_tr) * 0.8)
        X_fit, X_cal = X_tr[:cal_split], X_tr[cal_split:]
        y_fit, y_cal = y_tr[:cal_split], y_tr[cal_split:]

        # 1. Fit base RF on the fit set
        clf = RandomForestClassifier(**RF_PARAMS)
        clf.fit(X_fit, y_fit)

        # 2. Calibrate using prefit=True on the held-out calibration set
        calibrated_clf = train_calibrated_model(clf, X_cal, y_cal)

        # 3. Get calibrated probabilities for the validation fold
        probs = calibrated_clf.predict_proba(X_vl)

        # Report Platt calibration quality for this fold
        base_probs = clf.predict_proba(X_vl)
        n_cls = len(clf.classes_)
        one_hot_vl = np.eye(n_cls)[y_vl]
        fold_ll_base  = log_loss(y_vl, base_probs)
        fold_ll_calib = log_loss(y_vl, probs)
        fold_brier_base  = float(np.mean(np.sum((base_probs - one_hot_vl) ** 2, axis=1)))
        fold_brier_calib = float(np.mean(np.sum((probs      - one_hot_vl) ** 2, axis=1)))
        print(f"   Platt calibration — "
              f"log-loss: {fold_ll_base:.4f} → {fold_ll_calib:.4f} ({fold_ll_calib - fold_ll_base:+.4f}) | "
              f"Brier: {fold_brier_base:.4f} → {fold_brier_calib:.4f} ({fold_brier_calib - fold_brier_base:+.4f})")

        # 4. SHAP analysis on the base (uncalibrated) RF — TreeExplainer requires a tree model.
        #    Platt scaling is a monotonic sigmoid transform so relative feature importances are
        #    preserved: SHAP correctly explains which spectral features drive the RF's decisions.
        explainer = shap.TreeExplainer(clf)
        shap_values = explainer.shap_values(X_vl)

        if isinstance(shap_values, np.ndarray) and shap_values.ndim == 3:
            class_shap = [np.abs(shap_values[:, :, c]).mean(0) for c in range(shap_values.shape[2])]
        else:
            class_shap = [np.abs(s).mean(0) for s in shap_values]

        # 5. Compute SAM weights — clf.classes_ = [0..n-1], contiguous and aligned with label_array
        sam_weights_full = compute_sam_weights(X_vl, reference_library_array)
        sam_weights = sam_weights_full[:, calibrated_clf.classes_]  # (n_val, n_classes)

        # 6. Apply SAM weights to calibrated probabilities
        alpha = 1.33
        weighted_probs = probs * (sam_weights ** alpha)
        weighted_probs = np.nan_to_num(weighted_probs, nan=0.0)

        # Final predictions after applying SAM weights
        final_preds = calibrated_clf.classes_[np.argmax(weighted_probs, axis=1)]

        fold_importance.append(class_shap)
        scores = f1_score(y_vl, final_preds, average='macro')
        fold_scores.append(scores)
        acc = accuracy_score(y_vl, final_preds)
        fold_accuracies.append(acc)
        report = classification_report(y_vl, final_preds,
                                    target_names=dataset.molecule_names,
                                    zero_division=0)
        print(f"   Fold accuracy: {acc:.4f}")
        print(f"   Fold F1-score: {scores:.4f}")
        print(report)


    print("CROSS-VALIDATION SUMMARY")

    print(f"Per-fold accuracies : {[f'{a:.4f}' for a in fold_accuracies]}")
    print(f"Mean  accuracy      : {np.mean(fold_accuracies):.4f}")
    print(f"Std   accuracy      : {np.std(fold_accuracies):.4f}")
    print(f"Per-fold F1-scores  : {[f'{s:.4f}' for s in fold_scores]}")
    print(f"Mean  F1-score      : {np.mean(fold_scores):.4f}")
    print(f"Std   F1-score      : {np.std(fold_scores):.4f}")


    # Average feature importance across folds (np.mean absolute SHAP values)
    for class_idx in range(len(dataset.molecule_names)):
        
        # Extract per-class importance: list of n_folds arrays each of shape (n_features,)
        class_fold_importance = [imp[class_idx] for imp in fold_importance]
        plot_SHAP_stability(class_fold_importance, dataset.molecule_names[class_idx], top_n_features=10, output_dir=output_dir)

        class_importance = np.mean([imp[class_idx] for imp in fold_importance], axis=0)
        feature_indices = np.argsort(class_importance)[::-1][:10]  # Top 10 features
        print(f"\nTop features for class '{dataset.molecule_names[class_idx]}':")
        for idx in feature_indices:
            print(f"   Feature {idx} - Mean |SHAP|: {class_importance[idx]:.4f}")


    

    # ---------------------------------------------------------------------------
    # 4. Final evaluation on the held-out test set using best fold's model
    #    (retrain on the entire CV pool for a fair final estimate)
    # ---------------------------------------------------------------------------

    print("FINAL EVALUATION ON HELD-OUT TEST SET (model retrained on full CV pool)")

    # Train on 80% of CV pool; reserve 20% for Platt calibration — never touches the test set.
    cal_split = int(len(X_cv) * 0.8)
    final_clf = RandomForestClassifier(**RF_PARAMS)
    final_clf.fit(X_cv[:cal_split], y_cv[:cal_split])
    final_clf_platt = CalibratedClassifierCV(final_clf, cv='prefit', method='isotonic')
    final_clf_platt.fit(X_cv[cal_split:], y_cv[cal_split:])
    y_test_pred = final_clf_platt.predict(X_test)
    test_acc = accuracy_score(y_test, y_test_pred)

    # Calibration quality on the test set
    base_test_probs  = final_clf.predict_proba(X_test)
    calib_test_probs = final_clf_platt.predict_proba(X_test)
    n_cls = len(final_clf.classes_)
    one_hot_test = np.eye(n_cls)[y_test]
    print(f"  Final Platt calibration — "
          f"log-loss: {log_loss(y_test, base_test_probs):.4f} → {log_loss(y_test, calib_test_probs):.4f} | "
          f"Brier: {np.mean(np.sum((base_test_probs - one_hot_test)**2, axis=1)):.4f} "
          f"→ {np.mean(np.sum((calib_test_probs - one_hot_test)**2, axis=1)):.4f}")

    print(f"\nTest Accuracy: {test_acc:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_test_pred,
                                target_names=dataset.molecule_names,
                                zero_division=0))

    # ---------------------------------------------------------------------------
    # 5. Confusion matrix plots
    # ---------------------------------------------------------------------------
    cm = confusion_matrix(y_test, y_test_pred)

    for normalize, fmt, suffix in [(False, 'd', 'counts'), (True, '.2f', 'normalized')]:
        data = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis] if normalize else cm
        n = int(dataset.n_molecules)
        fig, ax = plt.subplots(figsize=(max(14, n // 2), max(12, n // 2)))
        sns.heatmap(data, annot=True, fmt=fmt, cmap='Blues',
                    xticklabels=dataset.molecule_names,
                    yticklabels=dataset.molecule_names,
                    ax=ax)
        ax.set_xlabel('Predicted', fontweight='bold')
        ax.set_ylabel('True',      fontweight='bold')
        ax.set_title(f'Confusion Matrix – {suffix} (Stratified {N_FOLDS}-Fold CV)',
                    fontweight='bold')
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        path = os.path.join(output_dir, f'stratified_kfold_cm_{suffix}.png')
        plt.savefig(path, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"Saved: {path}")

if __name__ == "__main__":
    main()